version: '3.7'

services:

  app:
    build: 
      context: .
    container_name: app
    volumes:
      - .:/usr/src/app
    tty: true
    ports:
      - "3333:3333"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge